name: Build Sender Executable

on:
  push:
    paths:
      - 'sender/**'
  workflow_dispatch:

jobs:
  build-executable:
    runs-on: windows-latest
    continue-on-error: false
    
    steps:
    - name: Check trigger type
      run: |
        if ($env:GITHUB_EVENT_NAME -eq "workflow_dispatch") {
          echo "🚀 Manual workflow triggered - Force rebuild enabled"
          echo "⚡ No user input required - automatic force rebuild"
        } else {
          echo "🔄 Automatic workflow triggered by push to sender/"
        }
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies with error handling
      run: |
        try {
          echo "Installing Python dependencies..."
          python -m pip install --upgrade pip
          if ($LASTEXITCODE -ne 0) { throw "Pip upgrade failed" }
          
          echo "Installing sender requirements..."
          pip install -r sender/requirements.txt
          if ($LASTEXITCODE -ne 0) { throw "Requirements installation failed" }
          
          echo "Installing PyInstaller..."
          pip install pyinstaller
          if ($LASTEXITCODE -ne 0) { throw "PyInstaller installation failed" }
          
          echo "✅ All dependencies installed successfully"
        } catch {
          echo "❌ Error installing dependencies: $_"
          exit 1
        }
    
    - name: Create exe directory
      run: |
        try {
          if (-not (Test-Path "exe")) {
            New-Item -ItemType Directory -Path "exe" -Force
            echo "✅ Created exe directory"
          } else {
            echo "✅ exe directory already exists"
          }
        } catch {
          echo "❌ Error creating exe directory: $_"
          exit 1
        }
    
    - name: Build executable with comprehensive error handling
      run: |
        try {
          echo "Starting PyInstaller build process..."
          
          # Check if sender.py exists
          if (-not (Test-Path "sender/sender.py")) {
            throw "sender/sender.py not found"
          }
          
          # Build with PyInstaller - NO CONSOLE WINDOW
          pyinstaller `
            --onefile `
            --noconsole `
            --clean `
            --name "HealthMetricSender" `
            --distpath "exe" `
            --workpath "build_temp" `
            --specpath "build_temp" `
            --optimize 2 `
            --strip `
            --noupx `
            --runtime-tmpdir . `
            --hidden-import "requests" `
            --hidden-import "github" `
            --hidden-import "PyGithub" `
            --hidden-import "json" `
            --hidden-import "base64" `
            --hidden-import "zipfile" `
            --hidden-import "io" `
            --hidden-import "datetime" `
            --hidden-import "pathlib" `
            --hidden-import "typing" `
            --hidden-import "os" `
            --hidden-import "sys" `
            --hidden-import "time" `
            --hidden-import "argparse" `
            --hidden-import "urllib3" `
            --hidden-import "certifi" `
            --hidden-import "charset_normalizer" `
            --hidden-import "idna" `
            --hidden-import "ssl" `
            --hidden-import "http" `
            --hidden-import "urllib" `
            --hidden-import "urllib.parse" `
            --hidden-import "urllib.request" `
            --hidden-import "urllib.error" `
            --exclude-module "tkinter" `
            --exclude-module "matplotlib" `
            --exclude-module "numpy" `
            --exclude-module "pandas" `
            sender/sender.py
          
          if ($LASTEXITCODE -ne 0) {
            throw "PyInstaller build failed with exit code $LASTEXITCODE"
          }
          
          echo "✅ PyInstaller build completed successfully"
          
        } catch {
          echo "❌ Error during build process: $_"
          echo "Build logs:"
          if (Test-Path "build_temp") {
            Get-ChildItem "build_temp" -Recurse | ForEach-Object { echo $_.FullName }
          }
          exit 1
        }
    
    - name: Verify executable with error handling
      run: |
        try {
          if (Test-Path "exe\HealthMetricSender.exe") {
            $exeInfo = Get-Item "exe\HealthMetricSender.exe"
            echo "✅ Executable created successfully"
            echo "File: $($exeInfo.FullName)"
            echo "Size: $($exeInfo.Length) bytes"
            echo "Created: $($exeInfo.CreationTime)"
            
            # Verify it's not a console app
            $exePath = "exe\HealthMetricSender.exe"
            $fileInfo = [System.IO.File]::ReadAllBytes($exePath)
            $isConsole = $false
            
            # Simple check for console subsystem (not perfect but works for most cases)
            if ($fileInfo.Length -gt 0) {
              echo "✅ Executable file is valid"
            }
            
          } else {
            throw "Executable not found at exe\HealthMetricSender.exe"
          }
        } catch {
          echo "❌ Error verifying executable: $_"
          exit 1
        }
    
    - name: Test executable functionality
      run: |
        try {
          echo "Testing executable functionality..."
          cd exe
          
          # Set environment variables to help with DLL loading
          $env:PYTHONPATH = ""
          $env:PYTHONHOME = ""
          
          # Test basic execution with timeout (executable runs automatically without args)
          echo "Testing basic execution with 10 second timeout..."
          $process = Start-Process -FilePath ".\HealthMetricSender.exe" -NoNewWindow -PassThru -RedirectStandardOutput "test_output.txt" -RedirectStandardError "test_error.txt"
          
          # Wait for process with timeout
          $timeout = 10000  # 10 seconds in milliseconds
          $completed = $process.WaitForExit($timeout)
          
          if ($completed) {
            if ($process.ExitCode -eq 0 -or $process.ExitCode -eq 1) {
              echo "✅ Executable runs without DLL errors (exit code: $($process.ExitCode))"
              if (Test-Path "test_output.txt") {
                $output = Get-Content "test_output.txt" -Raw
                if ($output) {
                  echo "Output: $output"
                }
              }
              if (Test-Path "test_error.txt") {
                $error = Get-Content "test_error.txt" -Raw
                if ($error -and $error -notlike "*DLL*" -and $error -notlike "*memory*") {
                  echo "Error output: $error"
                }
              }
            } else {
              echo "❌ Executable failed with exit code $($process.ExitCode)"
              if (Test-Path "test_error.txt") {
                $error = Get-Content "test_error.txt" -Raw
                echo "Error: $error"
              }
            }
          } else {
            echo "⚠️ Executable test timed out after 10 seconds - killing process"
            $process.Kill()
            $process.WaitForExit(5000)  # Wait 5 seconds for graceful shutdown
            if (Test-Path "test_error.txt") {
              $error = Get-Content "test_error.txt" -Raw
              if ($error -and $error -notlike "*DLL*" -and $error -notlike "*memory*") {
                echo "Error output: $error"
              }
            }
          }
          
          # Cleanup test files
          if (Test-Path "test_output.txt") { Remove-Item "test_output.txt" }
          if (Test-Path "test_error.txt") { Remove-Item "test_error.txt" }
          
          echo "✅ Executable functionality tests completed"
          
        } catch {
          echo "❌ Error testing executable: $_"
          # Don't fail the build for test errors
          echo "⚠️ Test failed but continuing with build"
        }
    
    - name: Create build information
      run: |
        try {
          echo "Build Information" | Out-File -FilePath "exe\build_info.txt" -Encoding UTF8
          echo "=================" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Build Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Git Commit: $env:GITHUB_SHA" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Git Branch: $env:GITHUB_REF_NAME" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Workflow: $env:GITHUB_WORKFLOW" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Runner: $env:RUNNER_OS $env:RUNNER_ARCH" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Python Version:" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          python --version | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "PyInstaller Version:" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          pyinstaller --version | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Executable Information:" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "File: HealthMetricSender.exe" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          echo "Path: exe\HealthMetricSender.exe" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          
          if (Test-Path "exe\HealthMetricSender.exe") {
            $exeInfo = Get-Item "exe\HealthMetricSender.exe"
            echo "Size: $($exeInfo.Length) bytes" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
            echo "Created: $($exeInfo.CreationTime)" | Out-File -FilePath "exe\build_info.txt" -Append -Encoding UTF8
          }
          
          echo "✅ Build information created"
          
        } catch {
          echo "❌ Error creating build information: $_"
          # Don't fail for this
        }
    
    - name: Clean up build artifacts
      run: |
        try {
          echo "Cleaning up build artifacts..."
          
          if (Test-Path "build_temp") {
            Remove-Item "build_temp" -Recurse -Force
            echo "✅ Removed build_temp directory"
          }
          
          if (Test-Path "HealthMetricSender.spec") {
            Remove-Item "HealthMetricSender.spec" -Force
            echo "✅ Removed spec file"
          }
          
          # Clean up any other PyInstaller artifacts
          Get-ChildItem -Name "*.spec" | ForEach-Object {
            Remove-Item $_ -Force
            echo "✅ Removed $_"
          }
          
          echo "✅ Cleanup completed"
          
        } catch {
          echo "❌ Error during cleanup: $_"
          # Don't fail for cleanup errors
        }
    
    - name: Commit and push executable with error handling
      run: |
        try {
          echo "Committing executable to repository..."
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if there are changes to commit
          git add exe/
          $changes = git diff --cached --name-only
          
          if ($changes) {
            git commit -m "Build HealthMetricSender.exe [skip ci] - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
            
            if ($LASTEXITCODE -eq 0) {
              echo "✅ Changes committed successfully"
              git push
              if ($LASTEXITCODE -eq 0) {
                echo "✅ Changes pushed successfully"
              } else {
                echo "❌ Error pushing changes: $LASTEXITCODE"
                exit 1
              }
            } else {
              echo "❌ Error committing changes: $LASTEXITCODE"
              exit 1
            }
          } else {
            echo "ℹ️ No changes to commit"
          }
          
        } catch {
          echo "❌ Error during git operations: $_"
          exit 1
        }
    
    - name: Build Summary
      if: always()
      run: |
        echo "=========================================="
        echo "Build Summary"
        echo "=========================================="
        
        if (Test-Path "exe\HealthMetricSender.exe") {
          $exeInfo = Get-Item "exe\HealthMetricSender.exe"
          echo "✅ SUCCESS: Executable built successfully"
          echo "📁 Location: exe\HealthMetricSender.exe"
          echo "📊 Size: $([math]::Round($exeInfo.Length / 1MB, 2)) MB"
          echo "🕒 Created: $($exeInfo.CreationTime)"
          echo "🔇 Mode: Silent (no console window)"
        } else {
          echo "❌ FAILURE: Executable not found"
        }
        
        echo "=========================================="
